version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    schedule:
      interval: "weekly"
    directory: "/"
    open-pull-requests-limit: 10
