version: "3.8"

services:
  fastapi-template-db:
    container_name: fastapi-template-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - type: volume
        source: fastapi-template-db-volume
        target: /var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  fastapi-template-db-volume:
    name: fastapi-template-db
    external: true
